@echo off
REM 启动 Chrome 并加载扩展
echo 启动 Chrome...
start "" "/c/Program Files/Google/Chrome/Application/chrome.exe" --user-data-dir="%USERPROFILE%\open-search-profile" --remote-debugging-port=9333 --remote-allow-origins=* --no-first-run --load-extension="/d/Agent/CC Place/浏览器自动化/open-search/vendor/chrome-extension"
echo 等待浏览器就绪...
timeout /t 3 /nobreak >nul
curl -s http://127.0.0.1:9333/json/version >nul 2>&1 && echo 浏览器已就绪 || echo 浏览器启动中，请稍候...
pause
